// export const AllGenre = Object.freeze({
//   Action: 'Action',
//   Adventure: 'Adventure',
//   Animation: 'Animation',
//   Comedy: 'Comedy',
//   Crime: 'Crime',
//   Drama: 'Drama',
//   Fantasy: 'Fantasy',
//   Horror: 'Horror',
//   Mystery: 'Mystery',
//   Romance: 'Romance',
//   SciFi: 'Sci-Fi',
//   Thriller: 'Thriller',
//   War: 'War',
//   Western: 'Western',
//   Documentary: 'Documentary',
//   Reality: 'Reality',
//   TalkShow: 'Talk Show',
//   Sitcom: 'Sitcom',
//   Superhero: 'Superhero',
//   Historical: 'Historical',
//   Family: 'Family',
//   Music: 'Music',
// });

export const AllGenre = [
  'Action',
  'Adventure',
  'Animation',
  'Comedy',
  'Crime',
  'Drama',
  'Fantasy',
  'Horror',
  'Mystery',
  'Romance',
  'Sci-Fi',
  'Thriller',
  'War',
  'Western',
  'Documentary',
  'Reality',
  'Talk Show',
  'Sitcom',
  'Superhero',
  'Historical',
  'Family',
  'Music',
] as const;
